server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://192.168.1.244:3306/dev_0524
        username: root
        password: QHyCTajI
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zyc.transactionpropagate.model